--Si sale error al crear usuario ejecutar
alter session set "_ORACLE_SCRIPT"=true;

--Creación de la TableSpace para los datos
CREATE TABLESPACE PROYECTODB_DAT 
    DATAFILE 'C:\ORACLEDB\ORADATA\XE\PROYECTODB_DAT.DBF' SIZE 5242880 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL;

--Creación de la TableSpace para los indices
CREATE TABLESPACE PROYECTODB_IDX 
    DATAFILE 'C:\ORACLEDB\ORADATA\XE\PROYECTODB_IDX.DBF' SIZE 5242880 AUTOEXTEND ON NEXT 1048576 MAXSIZE UNLIMITED 
    BLOCKSIZE 8192 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL;

--Creación de usuario para las TableSpaces creadas anteriormente
CREATE USER "PROYECTODB" PROFILE "DEFAULT" IDENTIFIED BY "proyectoDB2025"
DEFAULT TABLESPACE "PROYECTODB_DAT" TEMPORARY TABLESPACE "TEMP" ACCOUNT UNLOCK;

--Permisos para el usuario
GRANT "CONNECT" TO "PROYECTODB";
GRANT "RESOURCE" TO "PROYECTODB";

--Permisos sobre los objetos
GRANT ALTER ANY INDEX TO "PROYECTODB";
GRANT ALTER ANY SEQUENCE TO "PROYECTODB";
GRANT ALTER ANY TABLE TO "PROYECTODB";
GRANT ALTER ANY TRIGGER TO "PROYECTODB";
GRANT CREATE ANY INDEX TO "PROYECTODB";
GRANT CREATE ANY SEQUENCE TO "PROYECTODB";
GRANT CREATE ANY SYNONYM TO "PROYECTODB";
GRANT CREATE ANY TABLE TO "PROYECTODB";
GRANT CREATE ANY TRIGGER TO "PROYECTODB";
GRANT CREATE ANY VIEW TO "PROYECTODB";
GRANT CREATE PROCEDURE TO "PROYECTODB";
GRANT CREATE PUBLIC SYNONYM TO "PROYECTODB";
GRANT CREATE TRIGGER TO "PROYECTODB";
GRANT CREATE VIEW TO "PROYECTODB";
GRANT DELETE ANY TABLE TO "PROYECTODB";
GRANT DROP ANY INDEX TO "PROYECTODB";
GRANT DROP ANY SEQUENCE TO "PROYECTODB";
GRANT DROP ANY TABLE TO "PROYECTODB";
GRANT DROP ANY TRIGGER TO "PROYECTODB";
GRANT DROP ANY VIEW TO "PROYECTODB";
GRANT INSERT ANY TABLE TO "PROYECTODB";
GRANT QUERY REWRITE TO "PROYECTODB";
GRANT SELECT ANY TABLE TO "PROYECTODB";
GRANT UNLIMITED TABLESPACE TO "PROYECTODB";