-- =======================================
-- SECUENCIAS
-- =======================================

-- Secuencia para TBL_CLIENTES
CREATE SEQUENCE PROYECTODB.SEQ_CLIENTE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para TBL_CUENTAS
CREATE SEQUENCE PROYECTODB.SEQ_CUENTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para TBL_TRANSACCIONES
CREATE SEQUENCE PROYECTODB.SEQ_TRANSACCION
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para TBL_AUDITORIAS_TRANSACCION
CREATE SEQUENCE PROYECTODB.SEQ_AUDITORIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para TBL_USUARIOS
CREATE SEQUENCE PROYECTODB.SEQ_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para TBL_ROLES
CREATE SEQUENCE PROYECTODB.SEQ_ROL
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Secuencia para TBL_TIPOS_PARAMETROS
CREATE SEQUENCE PROYECTODB.SEQ_TIPO_PARAMETRO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;