-- =======================================
-- DATOS INICIALES: TIPOS DE PARÁMETROS
-- =======================================

-- TIPOS DE CUENTA (VALOR = 1)
INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'TIPO_CUENTA', 1, 'Cuenta de Ahorros');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'TIPO_CUENTA', 2, 'Cuenta Corriente');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'TIPO_CUENTA', 3, 'Cuenta de Nómina');

-- ESTADOS DE CUENTA (VALOR = 2)
INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'ESTADO', 1, 'Cuenta Activa');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'TIPO_CUENTA', 2, 'Cuenta Inactiva');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'TIPO_CUENTA', 3, 'Cuenta Bloqueada');

-- TIPOS DE TRANSACCIÓN (VALOR = 3)
INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'TIPO_TRANSACCION', 10, 'Depósito en Cuenta');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'TIPO_TRANSACCION', 11, 'Retiro de Cuenta');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'TIPO_TRANSACCION', 12, 'Transferencia entre Cuentas');

COMMIT;