-- =======================================
-- DATOS INICIALES: TIPOS DE PARÁMETROS
-- =======================================

-- TIPOS DE CUENTA (VALOR = 1)
INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'CUENTA_AHORRO', 1, 'Cuenta de Ahorros');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'CUENTA_CORRIENTE', 1, 'Cuenta Corriente');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'CUENTA_NOMINA', 1, 'Cuenta de Nómina');

-- ESTADOS DE CUENTA (VALOR = 2)
INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'ACTIVA', 2, 'Cuenta Activa');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'INACTIVA', 2, 'Cuenta Inactiva');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'BLOQUEADA', 2, 'Cuenta Bloqueada');

-- TIPOS DE TRANSACCIÓN (VALOR = 3)
INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'DEPOSITO', 3, 'Depósito en Cuenta');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'RETIRO', 3, 'Retiro de Cuenta');

INSERT INTO PROYECTODB.TBL_TIPOS_PARAMETROS (TIPO_PARAMETRO_ID, NOMBRE, VALOR, DESCRIPCION)
VALUES (SEQ_TIPO_PARAMETRO.NEXTVAL, 'TRANSFERENCIA', 3, 'Transferencia entre Cuentas');

COMMIT;