
DROP TABLE PROYECTODB.TBL_TRANSACCIONES CASCADE CONSTRAINTS;
CUIDADITO WAZAUSKI
DROP TABLE PROYECTODB.TBL_CUENTAS CASCADE CONSTRAINTS;
DROP TABLE PROYECTODB.TBL_CLIENTES CASCADE CONSTRAINTS;
DROP TABLE PROYECTODB.TBL_USUARIOS CASCADE CONSTRAINTS;
DROP TABLE PROYECTODB.TBL_ROLES CASCADE CONSTRAINTS;
DROP TABLE PROYECTODB.TBL_TIPOS_PARAMETROS CASCADE CONSTRAINTS;
DROP TABLE PROYECTODB.TBL_AUDITORIAS_TRANSACCION CASCADE CONSTRAINTS;
DROP TABLE PROYECTODB.TBL_LOG_ERRORES;


SECUENCIAS

DROP SEQUENCE PROYECTODB.SEQ_CLIENTE;
DROP SEQUENCE PROYECTODB.SEQ_CUENTA;
DROP SEQUENCE PROYECTODB.SEQ_TRANSACCION;
DROP SEQUENCE PROYECTODB.SEQ_AUDITORIA;
DROP SEQUENCE PROYECTODB.SEQ_USUARIO;
DROP SEQUENCE PROYECTODB.SEQ_ROL;
DROP SEQUENCE PROYECTODB.SEQ_TIPO_PARAMETRO;