-- =======================================
-- Tabla: TBL_CLIENTES
-- =======================================
CREATE TABLE PROYECTODB.TBL_CLIENTES(
        CLIENTE_ID VARCHAR2(20) NOT NULL,
        TELEFONO VARCHAR2(20) NOT NULL,
        EMAIL VARCHAR2(100) NOT NULL,
        NOMBRE VARCHAR2(50) NOT NULL,
        FECHA_REGISTRO DATE DEFAULT SYSDATE,
        IDENTIFICACION NUMBER(15) NOT NULL,
        DIRECCION VARCHAR2(50) NOT NULL,
        USUARIO_ID NUMBER
) TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX PK_IDX_CLIENTE_ID_CLIENTES
    ON PROYECTODB.TBL_CLIENTES(CLIENTE_ID)
    TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_CLIENTES
    ADD CONSTRAINT PK_CLIENTE_ID_CLIENTES
        PRIMARY KEY (CLIENTE_ID) USING INDEX PK_IDX_CLIENTE_ID_CLIENTES;


-- =======================================
-- Tabla: TBL_CUENTAS
-- =======================================
CREATE TABLE PROYECTODB.TBL_CUENTAS(
        CUENTA_ID VARCHAR2(20) NOT NULL,
        CLIENTE_ID VARCHAR2(20) NOT NULL,
        TIPO_CUENTA_ID NUMBER(10) NOT NULL,
        ESTADO_ID NUMBER(10) NOT NULL,
        FECHA_APERTURA DATE DEFAULT SYSDATE,
        SALDO NUMBER NOT NULL
) TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX PK_IDX_CUENTA_ID_CUENTAS
    ON PROYECTODB.TBL_CUENTAS(CUENTA_ID)
    TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_CUENTAS
    ADD CONSTRAINT PK_CUENTA_ID_CUENTAS
        PRIMARY KEY (CUENTA_ID) USING INDEX PK_IDX_CUENTA_ID_CUENTAS;


-- =======================================
-- Tabla: TBL_TRANSACCIONES
-- =======================================
CREATE TABLE PROYECTODB.TBL_TRANSACCIONES(
        TRANSACCION_ID NUMBER NOT NULL,
        CUENTA_ID VARCHAR2(20) NOT NULL,
        TIPO_TRANSAC_ID NUMBER(10) NOT NULL,
        MONTO NUMBER NOT NULL,
        FECHA_TRANSAC DATE NOT NULL
) TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX PK_IDX_TRANSACCION_ID_TRANSACCIONES
    ON PROYECTODB.TBL_TRANSACCIONES(TRANSACCION_ID)
    TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_TRANSACCIONES
    ADD CONSTRAINT PK_TRANSACCION_ID_TRANSACCIONES
        PRIMARY KEY (TRANSACCION_ID) USING INDEX PK_IDX_TRANSACCION_ID_TRANSACCIONES;



-- =======================================
-- Tabla: TBL_TIPOS_PARAMETROS
-- =======================================
CREATE TABLE PROYECTODB.TBL_TIPOS_PARAMETROS(
        TIPO_PARAMETRO_ID NUMBER NOT NULL,
        NOMBRE VARCHAR2(20) NOT NULL,
        VALOR NUMBER(10) NOT NULL,
        DESCRIPCION VARCHAR2(100) NOT NULL
) TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX PK_IDX_TIPO_PARAMETRO_ID_PARAMETROS
    ON PROYECTODB.TBL_TIPOS_PARAMETROS(TIPO_PARAMETRO_ID)
    TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_TIPOS_PARAMETROS
    ADD CONSTRAINT PK_TIPO_PARAMETRO_ID_PARAMETROS
        PRIMARY KEY (TIPO_PARAMETRO_ID) USING INDEX PK_IDX_TIPO_PARAMETRO_ID_PARAMETROS;


-- =======================================
-- Tabla: TBL_AUDITORIAS_TRANSACCION
-- =======================================
CREATE TABLE PROYECTODB.TBL_AUDITORIAS_TRANSACCION(
        AUDITORIA_ID NUMBER NOT NULL,
        TRANSACCION_ID NUMBER NOT NULL,
        USUARIO_ID NUMBER NOT NULL,
        MONTO_ANTERIOR NUMBER,
        MONTO_NUEVO NUMBER NOT NULL,
        TIPO_TRANSACCION_ANTERIOR NUMBER(10),
        TIPO_TRANSACCION_NUEVO NUMBER(10) NOT NULL,
        OPERACION VARCHAR2(20) NOT NULL,
        FECHA_OPERACION DATE NOT NULL
) TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX PK_IDX_AUDITORIA_ID_AUDITORIAS
    ON PROYECTODB.TBL_AUDITORIAS_TRANSACCION(AUDITORIA_ID)
    TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_AUDITORIAS_TRANSACCION
    ADD CONSTRAINT PK_AUDITORIA_ID_AUDITORIAS
        PRIMARY KEY (AUDITORIA_ID) USING INDEX PK_IDX_AUDITORIA_ID_AUDITORIAS;


-- =======================================
-- Tabla: TBL_USUARIOS
-- =======================================
CREATE TABLE PROYECTODB.TBL_USUARIOS(
        USUARIO_ID NUMBER NOT NULL,
        ROL_ID NUMBER(3) NOT NULL,
        USUARIO VARCHAR2(20) NOT NULL,
        PASSWORD VARCHAR2(64) NOT NULL
) TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX PK_IDX_USUARIO_ID_USUARIOS
    ON PROYECTODB.TBL_USUARIOS(USUARIO_ID)
    TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_USUARIOS
    ADD CONSTRAINT PK_USUARIO_ID_USUARIOS
        PRIMARY KEY (USUARIO_ID) USING INDEX PK_IDX_USUARIO_ID_USUARIOS;


-- =======================================
-- Tabla: TBL_ROLES
-- =======================================
CREATE TABLE PROYECTODB.TBL_ROLES(
        ROL_ID NUMBER(3) NOT NULL,
        NOMBRE VARCHAR2(20) NOT NULL
) TABLESPACE PROYECTODB_DAT;

CREATE UNIQUE INDEX PK_IDX_ROL_ID_ROLES
    ON PROYECTODB.TBL_ROLES(ROL_ID)
    TABLESPACE PROYECTODB_IDX;

ALTER TABLE PROYECTODB.TBL_ROLES
    ADD CONSTRAINT PK_ROL_ID_ROLES
        PRIMARY KEY (ROL_ID) USING INDEX PK_IDX_ROL_ID_ROLES;


-- =======================================
-- Tabla: TBL_LOG_ERRORES
-- =======================================
CREATE TABLE PROYECTODB.TBL_LOG_ERRORES (
        LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        FECHA_ERROR DATE DEFAULT SYSDATE,
        ORIGEN VARCHAR2(100),       
        MENSAJE_ERROR VARCHAR2(4000) 
) TABLESPACE PROYECTODB_DAT;


-- =======================================
-- FOREIGN KEYS
-- =======================================

-- USUARIOS → ROLES
ALTER TABLE PROYECTODB.TBL_USUARIOS
    ADD CONSTRAINT FK_USUARIOS_ROLES
        FOREIGN KEY (ROL_ID)
            REFERENCES PROYECTODB.TBL_ROLES(ROL_ID);

-- CUENTAS → CLIENTES
ALTER TABLE PROYECTODB.TBL_CUENTAS
    ADD CONSTRAINT FK_CUENTAS_CLIENTES
        FOREIGN KEY (CLIENTE_ID)
            REFERENCES PROYECTODB.TBL_CLIENTES(CLIENTE_ID);

-- CUENTAS → TIPOS_PARAMETROS
ALTER TABLE PROYECTODB.TBL_CUENTAS
    ADD CONSTRAINT FK_CUENTAS_TIPOS_PARAMETROS
        FOREIGN KEY (TIPO_CUENTA_ID)
            REFERENCES PROYECTODB.TBL_TIPOS_PARAMETROS(TIPO_PARAMETRO_ID);

-- CUENTAS → TIPOS_PARAMETROS (para ESTADO)
ALTER TABLE PROYECTODB.TBL_CUENTAS
    ADD CONSTRAINT FK_CUENTAS_TIPOS_PARAMETROS_ESTADO
        FOREIGN KEY (ESTADO_ID)
            REFERENCES PROYECTODB.TBL_TIPOS_PARAMETROS(TIPO_PARAMETRO_ID);

-- TRANSACCIONES → CUENTAS
ALTER TABLE PROYECTODB.TBL_TRANSACCIONES
    ADD CONSTRAINT FK_TRANSACCIONES_CUENTAS
        FOREIGN KEY (CUENTA_ID)
            REFERENCES PROYECTODB.TBL_CUENTAS(CUENTA_ID);

-- TRANSACCIONES → TIPOS_PARAMETROS
ALTER TABLE PROYECTODB.TBL_TRANSACCIONES
    ADD CONSTRAINT FK_TRANSACCIONES_TIPOS_PARAMETROS
        FOREIGN KEY (TIPO_TRANSAC_ID)
            REFERENCES PROYECTODB.TBL_TIPOS_PARAMETROS(TIPO_PARAMETRO_ID);

-- AUDITORIAS_TRANSACCION → TRANSACCIONES
ALTER TABLE PROYECTODB.TBL_AUDITORIAS_TRANSACCION
    ADD CONSTRAINT FK_AUDITORIAS_TRANSACCION_TRANSACCIONES
        FOREIGN KEY (TRANSACCION_ID)
            REFERENCES PROYECTODB.TBL_TRANSACCIONES(TRANSACCION_ID);

-- AUDITORIAS_TRANSACCION → USUARIOS
ALTER TABLE PROYECTODB.TBL_AUDITORIAS_TRANSACCION
    ADD CONSTRAINT FK_AUDITORIAS_TRANSACCION_USUARIOS
        FOREIGN KEY (USUARIO_ID)
            REFERENCES PROYECTODB.TBL_USUARIOS(USUARIO_ID);

ALTER TABLE PROYECTODB.TBL_CLIENTES
    ADD CONSTRAINT FK_CLIENTES_USUARIOS
        FOREIGN KEY (USUARIO_ID)
            REFERENCES PROYECTODB.TBL_USUARIOS(USUARIO_ID);

