-- =======================================
-- DATOS DE PRUEBA
-- =======================================

-- Insertar ROLES
INSERT INTO PROYECTODB.TBL_ROLES (ROL_ID, NOMBRE)
VALUES (SEQ_ROL.NEXTVAL, 'SUPERADMIN');

INSERT INTO PROYECTODB.TBL_ROLES (ROL_ID, NOMBRE)
VALUES (SEQ_ROL.NEXTVAL, 'ADMINISTRADOR');

INSERT INTO PROYECTODB.TBL_ROLES (ROL_ID, NOMBRE)
VALUES (SEQ_ROL.NEXTVAL, 'ANALISTA');

INSERT INTO PROYECTODB.TBL_ROLES (ROL_ID, NOMBRE)
VALUES (SEQ_ROL.NEXTVAL, 'CLIENTE');

-- Insertar USUARIOS (Nota: el password debería estar encriptado en producción)
INSERT INTO PROYECTODB.TBL_USUARIOS (USUARIO_ID, ROL_ID, USUARIO, PASSWORD)
VALUES (SEQ_USUARIO.NEXTVAL, 1, 'super_admin', 'admin123');

INSERT INTO PROYECTODB.TBL_USUARIOS (USUARIO_ID, ROL_ID, USUARIO, PASSWORD)
VALUES (SEQ_USUARIO.NEXTVAL, 2, 'admin', 'cajero123');

INSERT INTO PROYECTODB.TBL_USUARIOS (USUARIO_ID, ROL_ID, USUARIO, PASSWORD)
VALUES (SEQ_USUARIO.NEXTVAL, 3, 'jperez', 'cliente123');

INSERT INTO PROYECTODB.TBL_USUARIOS (USUARIO_ID, ROL_ID, USUARIO, PASSWORD)
VALUES (SEQ_USUARIO.NEXTVAL, 3, 'mgarcia', 'cliente123');

INSERT INTO PROYECTODB.TBL_USUARIOS (USUARIO_ID, ROL_ID, USUARIO, PASSWORD)
VALUES (SEQ_USUARIO.NEXTVAL, 4, 'lmartinez', 'cliente123');

-- Insertar CLIENTES (relacionados con usuarios de tipo CLIENTE)
INSERT INTO PROYECTODB.TBL_CLIENTES 
    (CLIENTE_ID, NOMBRE, IDENTIFICACION, DIRECCION, TELEFONO, EMAIL, USUARIO_ID)
VALUES 
    ('CLI-001', 'Juan Pérez López', 1234567890, 'Calle 10 #20-30, Cali', '3001112233', 'juan.perez@example.com', 3);

INSERT INTO PROYECTODB.TBL_CLIENTES 
    (CLIENTE_ID, NOMBRE, IDENTIFICACION, DIRECCION, TELEFONO, EMAIL, USUARIO_ID)
VALUES 
    ('CLI-002', 'María García Rodríguez', 9876543210, 'Carrera 5 #15-25, Cali', '3012223344', 'maria.garcia@example.com', 4);

INSERT INTO PROYECTODB.TBL_CLIENTES 
    (CLIENTE_ID, NOMBRE, IDENTIFICACION, DIRECCION, TELEFONO, EMAIL, USUARIO_ID)
VALUES 
    ('CLI-003', 'Luis Martínez Gómez', 5555555555, 'Avenida 3N #40-50, Cali', '3023334455', 'luis.martinez@example.com', 5);

INSERT INTO PROYECTODB.TBL_CLIENTES 
    (CLIENTE_ID, NOMBRE, IDENTIFICACION, DIRECCION, TELEFONO, EMAIL, USUARIO_ID)
VALUES 
    ('CLI-004', 'Ana Sánchez Torres', 7777777777, 'Calle 15 #30-40, Cali', '3034445566', 'ana.sanchez@example.com', NULL);

INSERT INTO PROYECTODB.TBL_CLIENTES 
    (CLIENTE_ID, NOMBRE, IDENTIFICACION, DIRECCION, TELEFONO, EMAIL, USUARIO_ID)
VALUES 
    ('CLI-005', 'Carlos Ramírez Cruz', 3333333333, 'Carrera 10 #25-35, Cali', '3045556677', 'carlos.ramirez@example.com', NULL);

-- Insertar CUENTAS (necesitas saber los IDs de los parámetros insertados antes)
-- Asumiendo: CUENTA_AHORRO=1, CUENTA_CORRIENTE=2, ACTIVA=4, INACTIVA=5

INSERT INTO PROYECTODB.TBL_CUENTAS (CUENTA_ID, CLIENTE_ID, TIPO_CUENTA_ID, ESTADO_ID, SALDO)
VALUES ('CTA-0001', 'CLI-001', 1, 4, 5000000);

INSERT INTO PROYECTODB.TBL_CUENTAS (CUENTA_ID, CLIENTE_ID, TIPO_CUENTA_ID, ESTADO_ID, SALDO)
VALUES ('CTA-0002', 'CLI-001', 2, 4, 2000000);

INSERT INTO PROYECTODB.TBL_CUENTAS (CUENTA_ID, CLIENTE_ID, TIPO_CUENTA_ID, ESTADO_ID, SALDO)
VALUES ('CTA-0003', 'CLI-002', 1, 4, 10000000);

INSERT INTO PROYECTODB.TBL_CUENTAS (CUENTA_ID, CLIENTE_ID, TIPO_CUENTA_ID, ESTADO_ID, SALDO)
VALUES ('CTA-0004', 'CLI-003', 2, 4, 1500000);

INSERT INTO PROYECTODB.TBL_CUENTAS (CUENTA_ID, CLIENTE_ID, TIPO_CUENTA_ID, ESTADO_ID, SALDO)
VALUES ('CTA-0005', 'CLI-003', 1, 5, 500000);

INSERT INTO PROYECTODB.TBL_CUENTAS (CUENTA_ID, CLIENTE_ID, TIPO_CUENTA_ID, ESTADO_ID, SALDO)
VALUES ('CTA-0006', 'CLI-004', 1, 4, 3000000);

INSERT INTO PROYECTODB.TBL_CUENTAS (CUENTA_ID, CLIENTE_ID, TIPO_CUENTA_ID, ESTADO_ID, SALDO)
VALUES ('CTA-0007', 'CLI-005', 2, 6, 0);

COMMIT;